### ISSUE TITLE
Humanoid:Move() not working

### ISSUE THREAD

**Issue by FirstVertex** [EgoMoose/Rbx-Gravity-Controller#6]
When using GravityController, and attempting to programmatically move the character, there is no effect.

I am using `Humanoid:Move()` during a Render Step as seen at the bottom of this page: https://developer.roblox.com/en-us/api-reference/function/Humanoid/Move

The player is wearing Rocket Skates and needs to be in constant forward motion.  You can see an example of that technique in the Roblox Studio New Game template "Line Runner" where the player is forced to always run forward.

**Comment by EgoMoose** [comment]
Humanoid:Move is not supported as it only tells us the world space move vector, not the local space vector. Since the controller expects a local space input that will then be converted as movement relative to a camera this will not be possible.
